name: reviewdog
on: [push, pull_request]
jobs:
  ktlint:
    name: Check ktlint
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: ktlint
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
  detekt:
    name: Check detekt
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: detekt
        uses: DominuS-RU/Detekt-Action@v1.16.0
        with:
          github_token: ${{ secrets.github_token }}
          detekt_config: config/detekt/detekt.yml
